app/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_user, login_required, logout_user, current_user, login_manager
from .models import User

views = Blueprint('views', __name__)

@views.route('/')
def landing():
    return render_template('landing.html')

@views.route('/profile')
@login_required
def profile():
    return render_template('profile.html')

@views.route('/user/<username>')
@login_required
def user(username):
    user = User.query.filter_by(username = username).first_or_404()
    courses = user.following
    return render_template('user.html', user=user, courses=courses)
    

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel ="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet">
        <title> Align </title>
</head>
<body>
    <header>
        <div class="navbar">
            <h2><a href="{{ url_for('views.landing') }}" class="logo"> Align </a></h2>
            <nav>
                <ul class="navbar-links">
                    <li class="nav-item"><a href="{{ url_for('views.landing') }}">About</a></li>
                    <li class="nav-item"><a href="{{ url_for('views.profile') }}">Profile</a></li>
                    <li class="nav-item"><a href="{{ url_for('auth.login') }}">Login</a></li>
                </ul>
                <div class="hamburger">
                    <span class="bar"></span>
                    <span class="bar"></span>
                    <span class="bar"></span>
                </div>
            </nav>
        </div>
    </header>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for msg in messages %}
            <div class="alert {{ category }}">
                <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                {{ msg }}
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

    <div class="content-container">
        <div class="padding-content"></div>
        <div class="content">
            {% block content %} {% endblock content %}
            <div class="padding-content"></div>
        </div>
    </div>
    <script src="/static/scripts.js"></script>
</body>
</html>

app/templates/join.html
{% extends "base.html" %}
{% block head %}
{% endblock %}

{% block content %}
<body>
    <title> Course List </title>
    <h1><u> Join A Course Today! </u></h1>
        <div class="input-form">
            <form class="form-class" id="course_choice" name="course_choice" method="post">
                <select class="form-group"id=course_name name="course_name">
                    {% for course in courses %}
                    <option value="{{ course.courseName }}">{{ course.courseName }}</option>
                    {% endfor %}
                </select>
                <br>
                <div class="form-button">
                    <button type="submit" class="input-button"> Sign Up </button>
                </div>            
            </form>
        </div>
    </body>
{% endblock %}

app/templates/landing.html
{% extends "base.html" %}
{% block head %}
{% endblock %}

{% block content %}
<h1><u> Landing Page </u></h1>
{% endblock content%}

app/templates/profile.html
{% extends "base.html" %}
{% block head %}
{% endblock %}

{% block content %}
<body>
    <h2 class="account-title">Welcome back {{ current_user.firstName +" "+ current_user.lastName }}!</h2>
    <p class="account-details"> Email: {{ current_user.email }}</p>
    <p class="account-details"> Username: {{ current_user.username }}</p>
    <h2><u> Update Your Details: </u></h2>
        <div class="input-form">
            <form class="form-class" method="POST">
                <div class="form-group">
                    <input type="email" id="new_email" name="new_email" placeholder="New Email" class="input-field">
                </div>
                <br>
                <div class="form-group">
                    <input type="text" id="new_username" name="new_username" placeholder="New Username" class="input-field">
                </div>
                <br>
                <div class="form-group">
                    <input type="text" id="new_firstName" name="new_firstName" placeholder="New First Name" class="input-field">
                </div>
                <br>
                <div class="form-group">
                    <input type="text" id="new_lastName" name="new_lastName" placeholder="New Last Name" class="input-field">
                </div>
                <br>
                <div class="form-button">
                    <button type="submit" class="input-button"> Update </button>
                </div>
            </form>
            </div>
                {% for course in courses_joined %}
                <div class="course-field"><h3><u>{{ course.courseName }}</u></dh3>
                    <br><h4>{{ course.courseInformation }}</h4>
                </div>
                {% endfor %}
            </div>
        </div>
</body>
{% endblock content %}

app/templates/user.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ user.firstName }}</h1>
    <hr>
    {% for course in courses %}
    <p>
    <h2>{{ course.courseName }}</h2>
        {{ course.courseInformation }}
    </p>
    {% endfor %}
{% endblock %}